### ISSUE TITLE
Help required with installion instructions

### ISSUE THREAD

**Issue by isuryadilip** [dhruvyad/uttertype#2]
Hi, 

I followed the install instruction on the page. I'm stuck at Step 4.

> 4. Add OpenAI API key
> Make sure that your OpenAI API key is available in the terminal environment either by directly exporting it as follows
> 
> export OPENAI_API_KEY=<your_openai_api_key>
> or creating a .env file in the directory with the following content
> 
> OPENAI_API_KEY=<your_openai_api_key>

I first ran export command and i got this error.

![Screenshot 2024-04-29 104839](https://github.com/dhruvyad/uttertype/assets/28861793/ff23e605-2273-4520-98fe-cc285b2f9695)

Then I created api_key.env file in uttertype DIR, and ran python main.py. Then i got the below error.

![image](https://github.com/dhruvyad/uttertype/assets/28861793/6c2295e7-0bf3-463f-9a32-3f352dd8e776)

Please help

**Comment by Frank-Z-Chen** [comment]
> Hi,
> 
> I followed the install instruction on the page. I'm stuck at Step 4.
> 
> > 4. Add OpenAI API key
> >    Make sure that your OpenAI API key is available in the terminal environment either by directly exporting it as follows
> > 
> > export OPENAI_API_KEY=<your_openai_api_key>
> > or creating a .env file in the directory with the following content
> > OPENAI_API_KEY=<your_openai_api_key>
> 
> I first ran export command and i got this error.
> 
> ![Screenshot 2024-04-29 104839](https://private-user-images.githubusercontent.com/28861793/326335067-ff23e605-2273-4520-98fe-cc285b2f9695.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjIxOTUsIm5iZiI6MTcxNTY2MTg5NSwicGF0aCI6Ii8yODg2MTc5My8zMjYzMzUwNjctZmYyM2U2MDUtMjI3My00NTIwLTk4ZmUtY2MyODViMmY5Njk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NjJiMzc2NTQ2YmJiYzk0OTc1MThjNWNjMTA4ZDM4OWE5NWFjNTMzYTBmNjExMGE1M2YzMjQ0NTk2ODU0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZPSwKeYxL6EHLkX2j1XbdMNuqTdXu-uKgKnmQknM55s)
> 
> Then I created api_key.env file in uttertype DIR, and ran python main.py. Then i got the below error.
> 
> ![image](https://private-user-images.githubusercontent.com/28861793/326333998-6c2295e7-0bf3-463f-9a32-3f352dd8e776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjIxOTUsIm5iZiI6MTcxNTY2MTg5NSwicGF0aCI6Ii8yODg2MTc5My8zMjYzMzM5OTgtNmMyMjk1ZTctMGJmMy00NjNmLTlhMzItM2YzNTJkZDhlNzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZmQ0NGVjYzIzMDNiYTc0YmVhYzNiNDhhZGE0MjNjODlkMjgyYTNhNGVhNjQ3MDA4NDc3NDMyYjZlYmQ1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CExTkhIWe2MlMr8FXEML_z-w_heT-cwxjzghyB8LEiY)
> 
> Please help

seems that you are using windows. windows does not use bash. Try this 
$env:OPENAI_API_KEY="<your key>"

**Comment by dhruvyad** [comment]
Yeah, you can do what Frank suggested or you can also create a `.env` file and put your API key there. I've updated the README based on @Frank-Z-Chen's comment for Windows for future reference.
